### ISSUE TITLE
Change default Mandrill port and flags

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer-wellknown#16]
Should be port 465 with `secure: true`, see my stream of tweets here: https://twitter.com/niftylettuce/status/694556328539193345
 
![screen shot 2016-02-02 at 11 22 32 am](https://cloud.githubusercontent.com/assets/523141/12755908/528db3d0-c99f-11e5-8368-dd4f7d9d8a1d.png)

**Comment by andris9** [comment]
I guess that Mandrill is using different TLS implementations for TLS on port 465 and STARTTLS on port 587, otherwise the result would be the same (connections to different ports would both either fail or succeed). Anyway, I do not want to change the defaults as there are no guarantees that the opposite situation would not happen - someone is currently successfully using TLS on port 587 but changing it to 465 in the background would break his application with no apparent reason.
